name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERIO_TOKEN }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hi5san/qnotebook:latest
    - name: Push the Docker image
      run: docker push hi5san/qnotebook:latest
    - name: Update repo description
      uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERIO_TOKEN }}
        repository: hi5san/qnotebook
        short-description: Simple Qiskit start jupyter lab container kit
        enable-url-completion: true
